name: angular_dart_demo
version: 0.0.1
dependencies:
  angular:
     git:
        url: git://github.com/angular/angular.dart.git #0.9.11 or later needed
        ref: HEAD
  browser: any
  js: any
  shadow_dom: any

dev_dependencies:
  unittest: any

transformers:
-  angular:
    html_files:
      - web/index.html